name: cdm-ci

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/cdm-ci
  cancel-in-progress: true

jobs:
  changes:
    runs-on: [ self-hosted, workflow-overhead ]
    outputs:
      real-ci: ${{ steps.filter.outputs.real-ci }}
      faux-ci: ${{ steps.filter.outputs.faux-ci }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            real-ci:
              - '**'
              - '!LICENSE'
              - '!**.md'
              - '!.github/rulesets/**'
              - '!.github/workflows/run-crucible-tracking.yaml'
              - '!.github/workflows/crucible-ci.yaml'
              - '!.github/workflows/cdm-ci.yaml'
              - '!docs/**'
            faux-ci:
              - 'LICENSE'
              - '**.md'
              - '.github/rulesets/**'
              - '.github/workflows/run-crucible-tracking.yaml'
              - '.github/workflows/crucible-ci.yaml'
              - '.github/workflows/cdm-ci.yaml'
              - 'docs/**'

  real-cdm-ci:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.real-ci == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22.22.0"
      - name: fail if javascript files are not formatted
        run: npx prettier **/*.js --check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  faux-cdm-ci:
    runs-on: [ self-hosted, workflow-overhead ]
    needs: changes
    if: ${{ needs.changes.outputs.faux-ci == 'true' && needs.changes.outputs.real-ci == 'false' }}
    steps:
      - run: 'echo "faux-cdm-ci-complete"'

  cdm-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    needs: [ real-cdm-ci, faux-cdm-ci ]
    # the always() will make this step run if one of the "needs" is
    # skipped (which should always be the case) but the other
    # completes successfully
    if: always()
    steps:
      - run: 'echo "cdm-ci complete"'
